apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-gitea-config
data:
  app.ini: |
    APP_NAME = simple-gitea
    RUN_MODE = prod
    RUN_USER = gitea

    [security]
    INTERNAL_TOKEN      = ${GITEA_INTERNAL_TOKEN}
    INSTALL_LOCK        = true
    SECRET_KEY          = ${GITEA_SECRET_KEY}
    PASSWORD_COMPLEXITY = off

    [oauth2]
    ENABLE = false

    [database]
    DB_TYPE  = postgres
    HOST     = postgresql-simple-gitea:5432
    NAME     = giteadb
    USER     = giteauser
    PASSWD   = giteapassword
    SSL_MODE = disable

    [repository]
    ROOT = /gitea-repositories

    [server]
    ROOT_URL         = https://simple-gitea-gitea.apps.ocp4.klaassen.click/
    SSH_DOMAIN       = simple-gitea-gitea.apps.ocp4.klaassen.click
    DOMAIN           = simple-gitea-gitea.apps.ocp4.klaassen.click
    HTTP_PORT        = 3000
    SSH_PORT         = 2022
    DISABLE_SSH      = False
    START_SSH_SERVER = False
    LFS_START_SERVER = False
    OFFLINE_MODE     = False

    [mailer]
    ENABLED = False
    [service]
    REGISTER_EMAIL_CONFIRM            = False
    ENABLE_NOTIFY_MAIL                = False
    DISABLE_REGISTRATION              = False
    ENABLE_CAPTCHA                    = False
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = True
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [webhook]
    ALLOWED_HOST_LIST = external,private
    SKIP_TLS_VERIFY = False

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /home/gitea/log

    [markup.asciidoc]
    ENABLED = true
    FILE_EXTENSIONS = .adoc,.asciidoc
    RENDER_COMMAND = "asciidoc --backend=xhtml11 --no-header-footer --attribute source-highlighter=source-highlight --out-file=- -"
    IS_INPUT_FILE = false

    [ssh.minimum_key_sizes]
    ED25519   = 256
    ECDSA     = 256
    RSA       = 3071
    DSA       = -1